# Generated by Django 4.2.3 on 2023-07-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prueba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_at',
        ),
    ]
