# Generated by Django 4.2.3 on 2023-07-11 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prueba', '0003_post_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Descripcion')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tipo_post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_prueba.tipopost', verbose_name='Tipo post'),
        ),
    ]
