# Generated by Django 4.2.3 on 2023-07-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prueba', '0004_tipopost_post_tipo_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.CharField(max_length=20, null=True, verbose_name='creado'),
        ),
    ]
